spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa


  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 업데이트 (create, update, validate 등)
    show-sql: true  # 실행된 SQL 쿼리 출력
    database-platform: org.hibernate.dialect.H2Dialect  # H2용 Hibernate Dialect 설정
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅

  h2:
    console:
      enabled: true
      path: /h2-console