spring:
  app:
    redirect-url: ${FRONTEND_REDIRECT_URL:http://localhost:5173}
    default-domain: ${DEFAULT_DOMAIN:localhost}
    backend-url: ${BACKEND_HOST:http://localhost:8080}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GCP_CLIENT_ID}
            client-secret: ${GCP_CLIENT_PASSWORD}
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/youtube.force-ssl
            redirect-uri: ${REDIRECT_URL_PATH:http://localhost:8080}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/auth
          token-uri: https://oauth2.googleapis.com/token
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          user-name-attribute: sub
data:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  cipher:
    secret-key: ${CRYPTO_KEY}