data:
  youtube:
    api-key: ${GCP_API_KEY}
    access-token: ${REDIS_GOOGLE_ACCESS_TOKEN}

  predict-server:
    scheme: ${PREDICT_SERVER_SCHEME:http}
    host: ${PREDICT_SERVER_HOST:localhost}
    port: ${PREDICT_SERVER_PORT:5000}