spring:
  application:
    name: youtube-comments

  config:
    import:
      - "classpath:/config/mariadb.yml"
      - "classpath:/config/redis.yml"
      - "classpath:/config/security.yml"
      - "classpath:/config/youtube-data.yml"
      - "classpath:/config/mongo.yml"

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false